version: "3.9"
services:
  imlca:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: imlca:noetic
    environment:
      DISPLAY: ${DISPLAY:-192.168.1.15:0}
      QT_X11_NO_MITSHM: "1"
      LIBGL_ALWAYS_SOFTWARE: "true"
      MESA_LOADER_DRIVER_OVERRIDE: swrast
      ROS_MASTER_URI: http://localhost:11311
      ROS_HOSTNAME: localhost
      LAUNCH_FILE: ${LAUNCH_FILE:-manual_controller_visuals.launch}
    volumes:
      - ..:/workspace:rw
    ports:
      - "11311:11311"
    stdin_open: true
    tty: true
