<?xml version="1.0"?>
<package format="2">
  <name>speed_visualizer</name>
  <version>0.0.0</version>
  <description>The speed_visualizer package</description>

  <maintainer email="michael.dessena@dxc.com">michael.dessena@dxc.com</maintainer>
  <license>TODO</license>

  <author email="michael.dessena@dxc.com">michael.dessena@dxc.com</author>

  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>rospy</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>lane_msgs</build_depend>

  <build_export_depend>rospy</build_export_depend>
  <build_export_depend>std_msgs</build_export_depend>
  <build_export_depend>lane_msgs</build_export_depend>

  <exec_depend>rospy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>lane_msgs</exec_depend>

  <export>
    <!-- Additional export information can go here -->
  </export>
</package>